### ISSUE TITLE
Allow to pick principle from the context item field

### ISSUE THREAD

**Issue by djay** [collective/sc.contentrules.localrole#2]
# Proposed change

In the configuration allow the user to optionally select from a list of fields on content types and then use that to get the principle to set the local role.

# Rationale 

This could be useful for many things but in particular it will let you setup a workflow where users pick from a drop down the user or group who are the reviewers of this form allowing it to be routed.

# Example

 - You have a workflow where you want to allow a certain group access to the content, depending on its workflow state. 
 - You also want the group that will have access to the content to be defined earlier in the workflow (e.g. through a selection of available users/groups)

# Requirements

 - Might need to fork to collective first #1 
 - Make compatible with Plone 5

**Comment by rodfersou** [comment]
This is the plan to make this change:

# Create a behavior
This behavior will be responsible to add a new field in the content type to set a group.
This field also should suggest a predefined groups (the groups already used in other objects).

# Create a new checkbox field in the content rule
This field is responsible to tell to use the behavior field to set the principal (when check this field should make principal field disabled).

@instification could you please review if this is a good plan?

**Comment by instification** [comment]
This is not a bad way of solving the problem (it's good to provide the behaviour as it can make it easier to user the functionatliy), but it's problematic.

What happens if somebody wants to create a custom field on their content object and use that? Your proposal forces the user to use the predefined behaviour. In our example, we want to have a field with a custom vocabulary to define the available users/groups.

Secondly, this only addresses the issue of adding the field to the content object, which is secondary to the functionality of being able to extract the value from the content object, then set the local role based on that.

For the initial iteration, it will be fine to have a free text box where the user enters the ID of the field they wish to use to get the user/group from. It's more important that the changes are able to cope well with a situation where the rule acts on a content object that doesn't have the chosen field.

In subsequent iterations we can add a widget that lets them select based on the possible options of fields (and indeed a field based on a behaviour can be one of those option). It is complicated because the content types that the content rule acts on can be filtered in the content rule conditions.

**Comment by rodfersou** [comment]
Okay, it looks like I still don't understand the use case.
 
I thought that the main reason of this change was to be able to fill the principal field in the object.

**Comment by rodfersou** [comment]
@instification how about to create a behavior and a control panel configlet with a text box to fill the content of the vocabulary used in this field?

The final use case will be the same as create a new field, but this looks to me to be a more explicit way.

**Comment by djay** [comment]
The final use case has a custom field with a set of groups defined by a custom vocabulary that is defined by the user.

Please go back to the requirements. A content rule which lets you pick any field to get the principle to get set the local role for. Your plan is more work and doesn’t solve the original problem.

**Comment by rodfersou** [comment]
> A content rule which lets you pick any field to get the principle.

This is the main problem here. You need one adapter for each field, explicitly (from the current implementation)
